version: '2.0'
services:
  wating_time_predict-green:
    container_name: wating_time_predict-green
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '8001:8000'